name: Deploy static HTML to GitHub Pages

on:
  push:
    branches: ["main"]   # Public repo'daki ana branch
  workflow_dispatch:      # Manuel tetikleme

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Root + data klasörünü Pages'e yükle
      - name: Upload static HTML
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'   # Repo kökünü deploy ediyor

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
